import { setup_tic_tac_toe } from "./Tictactoespiel.js";
export { sleep };
export { setupMainBereich };
export { resetMainbereich };
export { fetchJsonData };
export { sidenavHandler };
export { fetchTextData };
declare const resetMainbereich: () => HTMLDivElement[];
declare function setupMainBereich(): void;
declare function sleep(ms: number): Promise<unknown>;
declare function fetchJsonData(url: string): Promise<any>;
declare function fetchTextData(url: string): Promise<any>;
declare function sidenavHandler(): Object;
export declare function elementFactory(typ: string, attributes: any, style: string, ...children: any[]): HTMLElement;
export declare function setCssProperties(htmlElement: HTMLElement, props: string): void;
export declare function addToTable(table: HTMLTableElement, cellContent: any[][], headlinecontent: string[], colorHeadline?: string, colorRows?: string): void;
export { setup_tic_tac_toe };
