import { setup_tic_tac_toe } from "./Tictactoespiel.js";
export { sleep };
export { setupMainBereich };
export { MainBereichStyling };
export { resetMainbereich };
export { fetchJsonData };
export { sidenavHandler };
export { fetchTextData };
declare const resetMainbereich: () => HTMLDivElement[];
declare function setupMainBereich(): void;
declare function MainBereichStyling(): void;
declare function sleep(ms: number): Promise<unknown>;
declare function fetchJsonData(url: string): Promise<any>;
declare function fetchTextData(url: string): Promise<any>;
declare function sidenavHandler(): Object;
export { setup_tic_tac_toe };
